openapi: 3.0.3
info:
  title: Task Manager API
  version: 1.0.0
  description: API pour gérer des tâches (isofonctionnelle avec le contrôleur fourni).
servers:
  - url: /
tags:
  - name: Task
paths:
  /task:
    post:
      tags: [Task]
      operationId: createTask
      summary: Créer une tâche
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateDTO'
      responses:
        '202':
          description: Tâche acceptée/créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponseDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
    get:
      tags: [Task]
      operationId: listTasks
      summary: Liste de toutes les tâches
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponseDTO'

    delete:
      tags: [Task]
      operationId: deleteTask
      summary: Supprimer une tâche
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDeleteDTO'
      responses:
        '204':
          description: Supprimée
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /task/modifyStatus:
    patch:
      tags: [Task]
      operationId: modifyTaskStatus
      summary: Modifier le statut d'une tâche
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskChangeStatusDTO'
      responses:
        '202':
          description: Statut modifié
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponseDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /task/modifyUser:
    patch:
      tags: [Task]
      operationId: modifyTaskUser
      summary: Modifier l'utilisateur affecté
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskChangeUserAffecteeDTO'
      responses:
        '202':
          description: Utilisateur affecté modifié
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponseDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /task/allByStatus:
    get:
      tags: [Task]
      operationId: listTasksByStatus
      summary: Liste toutes les tâches groupées par statut
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskByStatusResponseDTO'

  /task/getTaskById/{taskId}:
    get:
      tags: [Task]
      operationId: getTaskById
      summary: Récupérer une tâche par son id
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponseDTO'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  responses:
    BadRequest:
      description: Requête invalide
    NotFound:
      description: Ressource non trouvée

  schemas:
    TaskStatus:
      type: string
      enum: [TODO, BLOCKED, DOING, TESTING, DONE]

    TaskCreateDTO:
      type: object
      required: [actor, title]
      properties:
        actor:
          type: string
          minLength: 1
        userAffectee:
          type: string
          nullable: true
        title:
          type: string
          minLength: 1
        description:
          type: string
          nullable: true
        priority:
          type: integer
          format: int32
          default: 0
        tags:
          type: array
          items:
            $ref: './tag.yaml#/components/schemas/TagCreateDTO'

    TaskChangeStatusDTO:
      type: object
      required: [actor, id, newStatus]
      properties:
        actor:
          type: string
          minLength: 1
        id:
          type: integer
          format: int64
        newStatus:
          $ref: '#/components/schemas/TaskStatus'

    TaskChangeUserAffecteeDTO:
      type: object
      required: [actor, id]
      properties:
        actor:
          type: string
          minLength: 1
        id:
          type: integer
          format: int64
        newUser:
          type: string
          nullable: true

    TaskDeleteDTO:
      type: object
      required: [actor, id]
      properties:
        actor:
          type: string
          minLength: 1
        id:
          type: integer
          format: int64

    TaskResponseDTO:
      type: object
      required: [id, title, status]
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
          nullable: true
        userAffectee:
          type: string
          nullable: true
        priority:
          type: integer
          format: int32
        tags:
          type: array
          items:
            $ref: './tag.yaml#/components/schemas/TagResponseDTO'
        status:
          $ref: '#/components/schemas/TaskStatus'

    TaskByStatusResponseDTO:
      type: object
      required: [TODO, BLOCKED, DOING, TESTING, DONE]
      properties:
        TODO:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponseDTO'
        BLOCKED:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponseDTO'
        DOING:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponseDTO'
        TESTING:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponseDTO'
        DONE:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponseDTO'